### ISSUE TITLE
Multiple youtube channel

### ISSUE THREAD

**Issue by abdallahmayuto** [hughred22/YouTube-Video-Listing-Ionic-Mobile-App#3]
How can I load videos from different youtube channel and display them in different menu?!

**Comment by hughred22** [comment]
It is actually very easy. You can use UI-ROUTER to create different states for different YouTube channels. Then in each state with its own controller, just replace the scope.youtubeParams to that channel IDs. You can also put the common codes in a factory so you don't repeat yourself. I am writing v3 tutorial for that as well.
